/**
 * The console background images that ship with the built-in themes, bundled
 * into the frontend as data: URLs (vite `?inline`) so the seeder can write
 * them next to the seeded theme JSON — a theme is its `.json` plus its
 * picture, and both must land in the themes folder together.
 *
 * Keyed by the bare file name the owning seed's `consoleBackground.image`
 * declares (core/theme-seeds.ts). The images themselves are generated by
 * `scripts/gen-theme-backgrounds.py` into `src/assets/theme-backgrounds/`.
 */

import abyssBg from '../assets/theme-backgrounds/abyss-bg.webp?inline';

/** Bare image file name → bundled `data:` URL. */
export const SEED_IMAGES: Readonly<Record<string, string>> = {
  'abyss-bg.webp': abyssBg,
};

/** The base64 payload of a bundled image (what `ipc.writeFileBase64` takes). */
export function seedImageBase64(name: string): string | undefined {
  const dataUrl = SEED_IMAGES[name];
  if (!dataUrl) {
    return undefined;
  }
  return dataUrl.slice(dataUrl.indexOf(',') + 1);
}
